In [1]:
#Melt & Pivot

import pandas as pd

df_copy=pd.read_csv('raw_data.csv')
df_copy['Name']=df_copy['Name'].bfill(inplace=True)
df_copy=df_copy.reset_index(drop=True)
df_copy.to_csv('raw_data.csv')

C:\Users\Dell\AppData\Local\Temp\ipykernel_10568\3261842251.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_copy['Name']=df_copy['Name'].bfill(inplace=True)

In [2]:
#melt and pivot
melted_df=df_copy.melt(        #expand data in rows
    id_vars=['Name','Id'],
    value_vars=['Salary','Salary_in_hand'],
    var_name='metrics',
    value_name='value'
)

melted_df.pivot( #expand in columns or back from melt
    index=['Name','Id'],
    columns='metrics',
    values='value'
)

metrics          Salary  Salary_in_hand
Name         Id
Ahmed Khan   6    73000           58400
             7    68000           54400
Alex         3    47000           37600
Carlos Ruiz  9    45000           36000
Emily Davis  10   58000           46400
Jane Smith   2    62000           49600
John Doe     1    55000           44000
Li Wei       5    51000           40800
Maria Garcia 4    45000           36000
Rachel Lee   8    62000           49600

In [3]:
#Merging and Joining
df_customers=pd.DataFrame({
    'cust_id':[1,2,3,4],
    'cust_name':['Harshit','Hua','Ksj','Gss']

})

df_orders=pd.DataFrame({
    'order_id':[101,102,103,104],
    'amount':[200,300,399,400],
    'cust_id':[2,1,4,5]
})

In [4]:
#inner join

pd.merge(df_customers,df_orders,on='cust_id')
pd.merge(df_customers,df_orders,on='cust_id',how='left')
pd.merge(df_customers,df_orders,on='cust_id',how='right')
pd.merge(df_customers,df_orders,on='cust_id',how='outer') #union

   cust_id cust_name  order_id  amount
0        1   Harshit     102.0   300.0
1        2       Hua     101.0   200.0
2        3       Ksj       NaN     NaN
3        4       Gss     103.0   399.0
4        5       NaN     104.0   400.0

In [ ]:
#data concatenation

pd.concat([df_customers,df_orders]) #rowise concat

#to reset row labels
pd.concat([df_customers,df_orders],ignore_index=True)

#columnwise concat
pd.concat([df_customers,df_orders],axis=1)

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Name,Age,Country,Gender,Salary,Tax(in %),Salary_in_hand,Rank,Id
0,0,0,0,0,Ahmed Khan,45,IN,F,73000,20,58400,1,6
1,1,1,1,1,Ahmed Khan,38,IN,M,68000,20,54400,2,7
2,2,2,2,2,Rachel Lee,29,US,F,62000,20,49600,3,8
3,3,3,3,3,Jane Smith,29,CAN,F,62000,20,49600,3,2
4,4,4,4,4,Emily Davis,31,US,F,58000,20,46400,4,10
5,5,5,5,5,John Doe,29,US,M,55000,20,44000,5,1
6,6,6,6,6,Li Wei,27,US,M,51000,20,40800,6,5
7,7,7,7,7,Alex,27,US,U,47000,20,37600,7,3
8,8,8,8,8,Carlos Ruiz,27,Mxco,M,45000,20,36000,8,9
9,9,9,9,9,Maria Garcia,34,SPN,F,45000,10,36000,8,4